### ISSUE TITLE
Can't make request with example

### ISSUE THREAD

**Issue by uzumaki258** [flowerchecker/Mushroom-id-API#1]
Hello, 
I try to request with your example, but it doesn't work.
```python
import base64
import requests

# encode images to base64
with open("mushroom.jpg", "rb") as file:
    images = [base64.b64encode(file.read()).decode("ascii")]

response = requests.post(
    "https://mushroom.mlapi.ai/api/v1/identification",
    json={
        "images": images,
        "similar_images": True,
    },
    headers={
        "Content-Type": "application/json",
        "Api-Key": "key",
    }).json()

print(response)
``` 
Here is the error: 
```shell
Traceback (most recent call last):
  File "/Users/bg/Work/API_Parse/ML_API/mushroom.py", line 8, in <module>
    response = requests.post(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
``` 

And I try in Postman, I got the error: Maximum images is set to 5, 116240 given.
I tested the attachment image, please help
![mushroom](https://github.com/flowerchecker/Mushroom-id-API/assets/26773292/eb2b116d-1831-45f5-999d-d19b34875d58)

**Comment by thran** [comment]
To debug your problem, please try to check `content` instead of `json()`. It contains error message.
I suspect that your image data are invalid, because you are trying send `"mushroom.py"` instead of a image.

I postman you probably forgot `[]` around your image.

**Comment by uzumaki258** [comment]
Hello @thranhave attachedk for your quick response. 
I attach the json data bellow
[data.json.zip](https://github.com/flowerchecker/Mushroom-id-API/files/11797518/data.json.zip)
Please check it. If possible can you please send me curl in your postman?

**Comment by thran** [comment]
> In postman you probably forgot `[]` around your image.

`images` has to be list of strings, you have only string.
